FROM registry.access.redhat.com/ubi9/go-toolset:1.26.7-1788409979 as builder
WORKDIR /workspace
# Dummy RUN to create /workspace directory.
# WORKDIR doesn't create the directory (at least for Podman).
# Without this step, the following COPY may create /workspace
# as root-owned (instead of go-toolset's default 1001)
# leading to "Permission denied" errors during "make build-operator"
# when trying to write output.
RUN ls .
COPY . /workspace
# Build
RUN make build-operator

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:7fbeae18dc9476399f565e68255f602a3374ea8614ba3d14843565131a13ff93
LABEL maintainer="Red Hat, Inc."
LABEL com.redhat.component="bgp-cloud-connector-operator"
LABEL name="bgpcc/bgp-cloud-connector-rhel9-operator"
LABEL version="0.1.0"
LABEL cpe="cpe:/a:redhat:bgp_cloud_connector:1.0::el9"
WORKDIR /
COPY --from=builder /workspace/bin/manager /
COPY LICENSE /licenses/
USER 65532:65532
ENTRYPOINT ["/manager"]
