#!/usr/bin/env bash
#
# Write the e2e profile describing the GCP estate that is standing.
#
#   hack/gcp/write-e2e-profile.sh <out-dir>
#
# Prints the directory it wrote, so a caller can hand it straight to
# E2E_MANIFEST_DIR.
#
# Generated rather than checked in, because a profile has to name the
# Cloud Router of the cluster it is run against and that is minted a
# minute earlier. The checked-in profiles under test/e2e/manifests
# cannot do that.
#
# The configuration carries spec.gcp and no spec.bgp.peerGroups. The CRD
# requires peer groups only under platform Manual and forbids them on
# every cloud, so naming them here would be rejected; the operator
# discovers the Cloud Router's interfaces and publishes them in
# status.peerGroups, which is what the suite asserts against.

set -o nounset
set -o errexit
set -o pipefail

# shellcheck source=hack/gcp/lib.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

out_dir="${1:-}"
[[ -n "${out_dir}" ]] || die "usage: ${0##*/} <out-dir>"

require_cmd gcloud oc
require_cluster
require_platform GCP
gcp_cluster_facts

router="$(gcp_router_name "${infra}")"
hub="$(gcp_hub_name "${infra}")"
spoke_prefix="$(gcp_spoke_prefix "${infra}")"

# The ASNs have to differ or the session is not eBGP, so this is checked
# rather than assumed. The Cloud Router's is whatever it was created
# with; ours is the localASN the profile is about to name.
router_asn="$(gcp_query "read the ASN of Cloud Router ${router}" \
    gcloud compute routers describe "${router}" --project="${project}" \
    --region="${region}" --format='value(bgp.asn)')" \
    || die "no Cloud Router ${router} in ${region}; stand the estate up first" \
           "  hack/gcp/create-cloud-router.sh"
local_asn="${LOCAL_ASN:-65001}"
[[ "${router_asn}" != "${local_asn}" ]] \
    || die "the Cloud Router and the cluster would share ASN ${local_asn}, which is not eBGP" \
           "Set LOCAL_ASN to something else, or rebuild the estate with a different ASN."

# Read rather than assumed, for the same reason the runbook says to read
# them: they have come out the same twice and that is not a guarantee.
addresses="$(gcp_router_interface_addresses "${router}" "${region}" "${project}")" \
    || die "could not read the interfaces of Cloud Router ${router}"
[[ -n "${addresses}" ]] \
    || die "Cloud Router ${router} reports no interface addresses, so nothing can peer with it"

# The label the repo's own tooling applies, not the one the older
# scripts used: hack/label-router-nodes.sh writes bgp_router=true, and
# spec.routerNodeSelector is what the operator selects on.
router_label_key="${ROUTER_LABEL_KEY:-bgp_router}"
router_label_value="${ROUTER_LABEL_VALUE:-true}"

# The CUDN subnet has to miss the cluster network, the service network
# and the VPC, or the advertisement collides with something the cluster
# already routes. 10.200.1.0/24 clears 10.128.0.0/14, 172.30.0.0/16 and
# the installer's 10.0.0.0/16.
cudn_name="${CUDN_NAME:-prod}"
cudn_subnet="${CUDN_SUBNET:-10.200.1.0/24}"

mkdir -p "${out_dir}"

cat > "${out_dir}/bgpcloudconfiguration.yaml" <<YAML
# Generated by hack/gcp/write-e2e-profile.sh. Do not edit: it describes
# whatever estate was standing when this ran.
apiVersion: networking.openshift.io/v1beta1
kind: BGPCloudConfiguration
metadata:
  name: cluster
spec:
  platform: GCP
  bgp:
    localASN: ${local_asn}
    livenessDetection: bgp-keepalive

  routerNodeSelector:
    ${router_label_key}: "${router_label_value}"

  gcp:
    project: ${project}
    region: ${region}
    cloudRouterName: ${router}
    ncc:
      hubName: ${hub}
      spokePrefix: ${spoke_prefix}
YAML

cat > "${out_dir}/bgprouting.yaml" <<YAML
# Generated by hack/gcp/write-e2e-profile.sh.
apiVersion: networking.openshift.io/v1beta1
kind: BGPRouting
metadata:
  name: cudn1
spec:
  network:
    name: ${cudn_name}
    subnets:
      - ${cudn_subnet}
YAML

warn "wrote a profile for ${router} (Cloud Router ASN ${router_asn}, local ASN ${local_asn}) to ${out_dir}"
warn "  interface addresses: $(printf '%s' "${addresses}" | tr '\n' ' ')"
printf '%s' "${out_dir}"
