apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: openshift-bgp-cloud-connector-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
