apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: openshift-bgp-cloud-connector
    control-plane: controller-manager
  name: openshift-bgp-cloud-connector-controller-manager-metrics-monitor
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    path: /metrics
    port: https
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: openshift-bgp-cloud-connector-controller-manager-metrics-service.openshift-bgp-cloud-connector.svc
  namespaceSelector:
    matchNames:
    - openshift-bgp-cloud-connector
  selector:
    matchLabels:
      app.kubernetes.io/name: openshift-bgp-cloud-connector
      control-plane: controller-manager
