apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: openshift-bgp-cloud-connector
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
