#!/usr/bin/env bash
#
# Write an e2e profile describing the estate that is actually up, and
# print the directory it went in.
#
#   hack/azure/write-e2e-profile.sh [<dir>]
#
# The profiles under test/e2e/manifests are written by hand against a
# cluster somebody keeps. That cannot work in CI, where the Route
# Server is created while the job is running, so the profile is
# generated instead, and generated somewhere temporary:
# E2E_MANIFEST_DIR lets the suite read it from outside the source tree,
# so a run leaves the repository exactly as it found it.
#
# Defaults to a fresh temporary directory. Pass one to keep it.

set -o nounset
set -o errexit
set -o pipefail

# shellcheck source=hack/azure/lib.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

local_asn="${LOCAL_ASN:-65001}"
cudn_name="${CUDN_NAME:-prod}"
cudn_subnet="${CUDN_SUBNET:-10.100.0.0/16}"
router_label_key="${ROUTER_LABEL_KEY:-bgp_router}"
router_label_value="${ROUTER_LABEL_VALUE:-true}"

require_cmd az oc
require_cluster
require_platform Azure
require_azure

# --- the ASN the nodes will advertise with ------------------------------
#
# Checked here rather than in the create script, because this is where
# the ASN is chosen: nothing the estate scripts build depends on it.
# Azure fixes the far side at 65515 and offers no flag to change it, so
# the only choice is the cluster's own.
#
# Verified against the Route Server FAQ, "What Autonomous System Numbers
# (ASNs) can I use?" and "Can I use 32-bit (4 byte) ASNs?", rather than
# carried over on trust.

[[ "${local_asn}" =~ ^[0-9]+$ ]] \
    || die "LOCAL_ASN is '${local_asn}', which is not a number"

# 16-bit only: the FAQ answers "Can I use 32-bit (4 byte) ASNs?" with a
# flat no. This bound also covers IANA's 65535-65551 reservation, since
# 65535 is already past it.
(( local_asn >= 1 && local_asn <= 65534 )) \
    || die "LOCAL_ASN ${local_asn} is not a 16-bit ASN" \
           "Azure Route Server supports 16-bit ASNs only, so 1-65534." \
           "The private range is 64512-65534."

case "${local_asn}" in
    8074|8075|12076|65515|65517|65518|65519|65520|23456)
        die "LOCAL_ASN ${local_asn} is reserved by Azure or IANA" \
            "Azure reserves 8074, 8075, 12076, 65515 and 65517-65520." \
            "IANA reserves 23456 and 64496-64511." \
            "65515 is the Route Server's own ASN, so a node advertising with it" \
            "puts that ASN in the AS_PATH and every route is discarded by" \
            "ordinary loop prevention while the session still reports" \
            "established -- healthy-looking and carrying nothing." \
            "Pick something in 64512-65514." ;;
esac

(( local_asn < 64496 || local_asn > 64511 )) \
    || die "LOCAL_ASN ${local_asn} is in IANA's reserved range 64496-64511" \
           "Pick something in 64512-65514."

# --- the estate that is up ----------------------------------------------

azure_cluster_facts
subscription="$(azure_subscription)" \
    || die "cannot tell which subscription az is pointed at"

rs="${infra}-rs"

# The far side's ASN, read from the Route Server rather than assumed.
# This doubles as the check that there is a Route Server at all: the
# profile names it, and a profile naming one that does not exist fails
# in the suite as a discovery problem rather than as a missing estate.
rs_asn="$(az_query "read the ASN of ${rs}" \
    az network routeserver list -g "${rg}" \
    --query "[?name=='${rs}'].virtualRouterAsn | [0]" -o tsv)" \
    || die "cannot read the Route Server ${rs} in ${rg}"

[[ -n "${rs_asn}" && "${rs_asn}" != "None" ]] \
    || die "no Route Server named ${rs} in ${rg}" \
           "Stand one up first: hack/azure/create-route-server.sh"

# Both are defaults that somebody will eventually change one of, so it
# is checked rather than assumed. Equal ASNs make the session iBGP,
# which is not what any of this is for.
[[ "${rs_asn}" != "${local_asn}" ]] \
    || die "localASN ${local_asn} equals the Route Server's ASN" \
           "They must differ, or the session is not eBGP." \
           "Azure fixes the Route Server's ASN, so change LOCAL_ASN."

out_dir="${1:-}"
[[ -n "${out_dir}" ]] || out_dir="$(mktemp -d)"
mkdir -p "${out_dir}"

# The neighbours are deliberately absent. spec.azure names the Route
# Server rather than its addresses, because the operator reads
# virtualRouterIps and virtualRouterAsn from Azure itself, and it sets
# ebgpMultiHop on every neighbour because the Route Server sits in its
# own subnet rather than on the node's link.
cat > "${out_dir}/bgpcloudconfiguration.yaml" <<EOF
# Generated by hack/azure/write-e2e-profile.sh. Do not edit: it
# describes whatever estate was standing when this ran.
apiVersion: networking.openshift.io/v1beta1
kind: BGPCloudConfiguration
metadata:
  name: cluster
spec:
  platform: Azure
  bgp:
    localASN: ${local_asn}
    livenessDetection: bgp-keepalive

  routerNodeSelector:
    ${router_label_key}: "${router_label_value}"

  azure:
    subscriptionID: ${subscription}
    resourceGroup: ${rg}
    routeServerName: ${rs}
EOF

cat > "${out_dir}/bgprouting.yaml" <<EOF
# Generated by hack/azure/write-e2e-profile.sh.
apiVersion: networking.openshift.io/v1beta1
kind: BGPRouting
metadata:
  name: cudn1
spec:
  network:
    name: ${cudn_name}
    subnets:
      - ${cudn_subnet}
EOF

warn "wrote a profile for ${rs} (route server ASN ${rs_asn}, local ASN ${local_asn}) to ${out_dir}"
printf '%s' "${out_dir}"
