#!/usr/bin/env bash
#
# Write an e2e profile describing the estate that is actually up, and
# print the directory it went in.
#
#   hack/aws/write-e2e-profile.sh [<dir>]
#
# The profiles under test/e2e/manifests pin a route server id, which is
# fine for one written by hand against a cluster you keep and useless
# for CI: the id is minted while the job runs. So the profile is
# generated, and generated somewhere temporary -- E2E_MANIFEST_DIR lets
# the suite read it from outside the source tree, so a run leaves the
# repository exactly as it found it.
#
# Defaults to a fresh temporary directory. Pass one to keep it.

set -o nounset
set -o errexit
set -o pipefail

# shellcheck source=hack/aws/lib.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

local_asn="${LOCAL_ASN:-65001}"
cudn_name="${CUDN_NAME:-prod}"
cudn_subnet="${CUDN_SUBNET:-10.100.0.0/16}"
router_label_key="${ROUTER_LABEL_KEY:-bgp_router}"
router_label_value="${ROUTER_LABEL_VALUE:-true}"

require_cmd aws oc
require_cluster
require_platform AWS
require_aws
aws_cluster_facts

out_dir="${1:-}"
if [[ -z "${out_dir}" ]]; then
    out_dir="$(mktemp -d)"
fi
mkdir -p "${out_dir}"

rs="$(route_server_for_cluster "${infra}")" \
    || die "cannot look up the route server for ${infra}"
[[ -n "${rs}" ]] || die "no route server tagged ${infra}-rs in ${region}" \
    "Stand one up first: hack/aws/create-route-servers.sh"

# The Amazon side and the cluster side must differ or the session is
# iBGP and never comes up. Checked rather than assumed, because both
# values are defaults that somebody will eventually change one of.
amazon_asn="$(aws_query "read the ASN of ${rs}" \
    aws ec2 describe-route-servers --route-server-ids "${rs}" \
    --query 'RouteServers[0].AmazonSideAsn' --output text)" \
    || die "cannot read the ASN of ${rs}"
[[ "${amazon_asn}" != "${local_asn}" ]] \
    || die "localASN ${local_asn} equals the route server's Amazon-side ASN" \
           "They must differ, or the session is not eBGP." \
           "Set LOCAL_ASN, or ASN when creating the route server."

cat > "${out_dir}/bgpcloudconfiguration.yaml" <<EOF
# Generated by hack/aws/write-e2e-profile.sh. Do not edit: the route
# server id below is whatever was standing when this ran.
apiVersion: networking.openshift.io/v1beta1
kind: BGPCloudConfiguration
metadata:
  name: cluster
spec:
  platform: AWS
  bgp:
    localASN: ${local_asn}
    livenessDetection: bgp-keepalive

  routerNodeSelector:
    ${router_label_key}: "${router_label_value}"

  aws:
    region: ${region}
    routeServerIDs:
      - ${rs}
EOF

cat > "${out_dir}/bgprouting.yaml" <<EOF
# Generated by hack/aws/write-e2e-profile.sh.
apiVersion: networking.openshift.io/v1beta1
kind: BGPRouting
metadata:
  name: cudn1
spec:
  network:
    name: ${cudn_name}
    subnets:
      - ${cudn_subnet}
EOF

warn "wrote a profile for ${rs} (amazon ASN ${amazon_asn}, local ASN ${local_asn}) to ${out_dir}"
printf '%s' "${out_dir}"
